main: com.gmail.woodyc40.lagger.Lagger
name: Lagger
version: 1.0-SNAPSHOT
api-version: "1.13"

commands:
  pause:
    usage: /pause [time]
    description: Pauses the server and lags the main thread for [time] seconds
  ohi:
    usage: /ohi [name] [verbose]
    description: Opens an inventory containing a skull of the player named [name]
  psniff:
    usage: /psniff [on | off | dump | filter] [arg]
    description: Toggles on/off packet sniffing and dumping or adds a filter term
  esniff:
    usage: /esniff [on | off | dump | filter] [arg]
    description: Toggles on/off event sniffing and dumping or adds an event
  chunk:
    usage: /chunk [load | unload | reload | help] [loaded]
    description: Allows simple manual control of chunk functionality
  ci:
    usage: /ci
    description: Clears the inventory of whoever is running the command